spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blue?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  mail:
    host: smtp.qq.com
    port: 587
    username: 462014555@qq.com
    password: dfhxdaqvsrvmcaci
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  file:
    name: C:/Users/46201/Desktop/ai-image-log.txt
  logback:
    rollingpolicy:
      max-history: 3
      max-file-size: 50MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  dashscope-api-key: sk-af8375bb801743cb8dccd5b76e62ecc9
  deepseek-api-key: sk-2953659abdc44c8bbdafbc6fa49d0e68
  openrouter-api-key: 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
  lk888-api-key: sk-862109526e96c8d06f4c789717481204c0183b4cfa10a9f9
  image2-provider: lk888
  public-url: http://47e9a9ab.r2.cpolar.top
  proxy-host: 127.0.0.1
  proxy-port: 7897
  batch-size: 200
  retry-times: 3
  sleep-ms: 1000
  output-dir: output
  paddleocr-endpoint: http://127.0.0.1:8866
  chrome-path: C:\Users\46201\AppData\Local\Google\Chrome\Application\chrome.exe
  chrome-debug:
    9222: C:\chrome-debug-1688
    9223: C:\chrome-debug-merchant
    9224: C:\chrome-debug-taobao
  taobao-target-url: https://sxkc.wusetech.com/administrator-list
  supplement-image-dir: C:\Users\46201\Pictures\补单

