spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blue?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  mail:
    host: smtp.qq.com
    port: 587
    username: 462014555@qq.com
    password: dfhxdaqvsrvmcaci
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  dashscope-api-key: ${DASHSCOPE_API_KEY:}
  batch-size: 200
  retry-times: 3
  sleep-ms: 1000
  output-dir: output
  paddleocr-endpoint: http://127.0.0.1:8866
  chrome-path: C:\Users\46201\AppData\Local\Google\Chrome\Application\chrome.exe
  chrome-debug:
    9222: C:\chrome-debug-1688
    9223: C:\chrome-debug-merchant
    9224: C:\chrome-debug-taobao
  taobao-target-url: https://sxkc.wusetech.com/administrator-list

